name: Android CI

on:
  push:
    branches: [ "main", "test" ]  # Added test branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17 for AGP 8.8.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Create local.properties with dummy API key for CI builds
      - name: Create local.properties for CI
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "GOOGLE_MAPS_API_KEY=dummy_key_for_ci_build" >> local.properties

      # Cache Gradle dependencies for faster builds
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run lint checks
      - name: Run Lint
        run: ./gradlew lintDebug

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # Build project (includes assemble)
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      # Upload test results
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: unit-test-results
          path: |
            app/build/reports/tests/testDebugUnitTest/
            app/build/test-results/testDebugUnitTest/

      # Upload lint results
      - name: Upload Lint Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results
          path: app/build/reports/lint-results-debug.html

      # Comment test results on PR (if it's a PR)
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && github.event_name == 'pull_request'
        with:
          files: |
            app/build/test-results/testDebugUnitTest/*.xml